### PR TITLE
Digitrust 227 ci cd for tob issuer controllers

### PR DESCRIPTION
**Pull request by jon-funk**
# Description

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jon-funk** [comment]
- Needs secrets added
- Pending doc changes that will be pushed to test the ansible playbook before PR merged
- See ansible/README.md for details

**Comment by jon-funk** [comment]
Secrets and docs updated

**Review by Jsyro — COMMENTED** [review]
Fabulous work Jon, i'll wait for Sherman to take a look.

**Review by parc-jason — APPROVED** [review]
this is awesome stuff 👍 👍

**Pull request merged**
